version: '3'
services:
  nginx:
    build: ./nginx/
    image: ${GLOBAL_PROJECT_NAME}/nginx:latest
    container_name: "${GLOBAL_PROJECT_NAME}_nginx"
    volumes:
      - ./www:/var/www/html:rw
      - ./nginx/${GLOBAL_NGINX_ENV}/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/${GLOBAL_NGINX_ENV}/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs:/var/log/nginx:rw
    ports:
      - "443:443"
      - "80:80"
    networks:
      - ec_network
