version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "443:443"
      - "80:80"
      - "81:81"
      - "90:90"
    networks:
      - test1

    volumes:
      - ./www/:/var/www/html/:rw
      - ./conf/nginx/conf.d:/etc/nginx/conf.d/:ro
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./log/nginx/:/var/log/nginx/:rw
    networks:
      - test1
    depends_on:
      - php72
      - php56
      - nodejs
  
  php72:
    build: 
      context: ./php/
      dockerfile: ./php72/Dockerfile
    expose:
      - "9000"
    volumes:
      - ./www/:/var/www/html/:rw
      - ./conf/php/php72/php.ini:/usr/local/etc/php/php.ini:ro
      - ./conf/php/php72/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./log/php-fpm/php72/:/var/log/php-fpm/:rw
    networks:
      - test1
    depends_on:
      - mysql
      - redis
  
  php56:
    build: 
      context: ./php/
      dockerfile: ./php56/Dockerfile
    expose:
      - "9000"
    volumes:
      - ./www/:/var/www/html/:rw
      - ./conf/php/php56/php.ini:/usr/local/etc/php/php.ini:ro
      - ./conf/php/php56/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./log/php-fpm/php56/:/var/log/php-fpm/:rw
    networks:
      - test1
    depends_on:
      - mysql
      - redis
  
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - ./conf/mysql/my.cnf:/etc/mysql/my.cnf:ro
      - ./mysql/:/var/lib/mysql/:rw
      - ./log/mysql/:/var/log/mysql/:rw
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    networks:
      - test1
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - test1
  
  nodejs:
    build: ./nodejs/
    # ports:
    #   - "3000:3000"
    volumes:
      - ./www/myapp:/home/myapp:rw
    networks:
      - test1
      
networks:
    test1:
      driver: bridge