version: '3'
services:
  postgres:
    image: ${GLOBAL_PROJECT_NAME}/postgres:latest
    build: ./postgres/
    container_name: "${GLOBAL_PROJECT_NAME}_postgres"
    volumes:
        - ./postgres/data:/var/lib/postgresql/data
    environment:
        - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"
    networks:
      - ec_network