version: '3'
services:
  redis:
    build: ./redis/
    image: ${GLOBAL_PROJECT_NAME}/redis:latest
    container_name: "${GLOBAL_PROJECT_NAME}_redis"
    ports:
      - "6379:6379"
    networks:
      - ec_network